export const demoEvents = [
    {
        id: 1,
        sig: 'Dev',
        title: 'Building Scalable Web Applications with the Latest Frameworks',
        date_time: '2024-04-15T10:00:00.000Z',
        event_type: 'Online', 
        location: 'Nitk main building',
        link: 'https://www.google.com',
        cems_link: 'https://www.google.com',
        body: 'Explore the latest trends and innovations in web development at TechCon 2024. Join experts, network with industry leaders, and witness groundbreaking presentations.',
        cover_image: 'https://source.unsplash.com/400x400/?servers',
        resources: ['Keynote Speakers', 'Workshops', 'Networking Sessions'],
    },
    {
        id: 2,
        sig: 'Algo',
        title: 'Mastering Algorithms: From Basics to Advanced Techniques',
        date_time: '2024-05-20T17:30:00.000Z',
        event_type: 'Online', 
        location: 'Nitk LHC-A',
        link: 'https://www.google.com',
        cems_link: 'https://www.google.com',
        body: 'Dive deep into the world of algorithms at the Algorithm Workshop 2024. This hands-on workshop will cover a range of algorithms, from fundamentals to advanced techniques.',
        cover_image: 'https://source.unsplash.com/400x400/?algorithms',
        resources: ['Interactive Coding Sessions', 'Q&A with Experts', 'Algorithm Challenges'],
    },
    {
        id: 3,
        sig: 'Systems',
        title: 'Revolutionizing IT Infrastructure: The Future of Systems Design',
        date_time: '2024-06-10T14:00:00.000Z',
        event_type: 'Online', 
        location: 'Nitk CDS',
        link: 'https://www.google.com',
        cems_link: 'https://www.google.com',
        body: 'Join us at the Systems Summit 2024 to explore the future of IT infrastructure. Learn about the latest advancements in systems design, network with professionals, and gain insights into optimizing performance.',
        cover_image: 'https://source.unsplash.com/400x400/?internet',
        resources: ['Panel Discussions', 'Hands-on Labs', 'Networking Sessions'],
    },
    {
        id: 4,
        sig: 'Intel',
        title: 'Unleashing the Power of Artificial Intelligence: Intel Tech Forum',
        date_time: '2024-07-05T11:00:00.000Z',
        event_type: 'Online', 
        location: 'Nitk main building',
        link: 'https://www.google.com',
        cems_link: 'https://www.google.com',
        body: 'Explore the cutting-edge advancements in artificial intelligence at the Intel Tech Forum 2024. Engage with thought leaders, witness live demonstrations, and discover how AI is shaping the future.',
        cover_image: 'https://source.unsplash.com/400x400/?artificial-intelligence',
        resources: ['AI Demos', 'Expert Panels', 'Innovation Showcases'],
    },
    {
        id: 5,
        sig: 'Dev',
        title: 'Next-Gen Developer Summit: Crafting the Future of Software Engineering',
        date_time: '2024-08-15T09:30:00.000Z',
        event_type: 'Online', 
        location: 'Nitk LHC-A',
        link: 'https://www.google.com',
        cems_link: 'https://www.google.com',
        body: 'Join us at the Next-Gen Developer Summit 2024 to explore the latest trends and techniques in software engineering. Connect with fellow developers, attend hands-on workshops, and discover the tools shaping the future.',
        cover_image: 'https://source.unsplash.com/400x400/?google',
        resources: ['Coding Challenges', 'Tech Talks', 'Interactive Workshops'],
    },
    {
        id: 6,
        sig: 'Algo',
        title: 'Quantum Algorithms Symposium: Navigating the Quantum Frontier',
        date_time: '2024-09-20T15:00:00.000Z',
        event_type: 'Online', 
        location: 'Nitk CDS',
        link: 'https://www.google.com',
        cems_link: 'https://www.google.com',
        body: 'Explore the forefront of quantum computing at the Quantum Algorithms Symposium 2024. Dive into discussions on quantum algorithms, participate in live experiments, and gain insights into the future of computation.',
        cover_image: 'https://source.unsplash.com/400x400/?quantum-computing',
        resources: ['Quantum Coding Challenges', 'Expert Panels', 'Hands-on Quantum Experiments'],
    },
    {
        id: 7,
        sig: 'Intel',
        title: 'Intellectual Ventures Forum: Shaping the Future of Intellectual Property',
        date_time: '2024-10-12T13:30:00.000Z',
        event_type: 'Online', 
        location: 'Nitk main building',
        link: 'https://www.google.com',
        cems_link: 'https://www.google.com',
        body: 'Join us at the Intellectual Ventures Forum 2024 to explore the evolving landscape of intellectual property. Engage with industry leaders, attend workshops on IP strategies, and discuss the impact of technology on innovation.',
        cover_image: 'https://source.unsplash.com/400x400/?deep-learning',
        resources: ['IP Strategy Workshops', 'Legal Insights', 'Networking with IP Professionals'],
    },
];