export const demoMembers = [
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
    {
        id: 1,
        name: "Hariharan",
        sig: "GDSC",
        role: "Webmaster",
        github_id: "https://github.com/j-hariharan/",
        linkedin_id: "https://www.linkedin.com/in/hariharan-j-47aa43244/",
        mail_id: "jhariharan2004@gmail.com",
        twitter_id: "https://twitter.com/",
        alumnus: false,
        image: "/test_profile.jpg"
    },
]