FROM node:20 AS builder
WORKDIR /app
RUN npm install -g corepack@latest
RUN corepack enable pnpm
COPY ./package.json .
RUN pnpm i
VOLUME [ "/app/node_modules", "/app/.next" ]
CMD ["pnpm", "run", "dev"]