services:

    db:
        image: postgres:14-bookworm
        restart: always
        environment:
            POSTGRES_USER: ${DATABASE_USERNAME}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            -   wec_backend_database:/var/lib/postgresql/data
        command: -p ${DATABASE_PORT}

    strapi:
        build:
            dockerfile: Dockerfile.dev
            context: "./backend"
            args:
                - BACKEND_URL=${BACKEND_URL}

        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}"]
            interval: 30s
            timeout: 30s
            retries: 5
            start_period: 50s
            start_interval: 10s
        depends_on:
            - db
        volumes:
            -   type: bind
                source: ./backend
                target: /app
        env_file:
            - .env
        
    
    frontend:
        build: 
            dockerfile: Dockerfile.dev
            context: "./frontend"
        depends_on:
            strapi:
                condition: service_healthy
                restart: true
        environment:
            - PORT=${FRONTEND_PORT}
        env_file:
            - .env
        volumes:
            -   type: bind
                source: ./frontend
                target: /app

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
            args:
                - FRONTEND_PORT=${FRONTEND_PORT}
                - BACKEND_PORT=${BACKEND_PORT}
        ports:
            - "${APPLICATION_PORT}:80"
        env_file:
            - .env
        depends_on:
            - strapi
            - frontend

volumes:
    wec_backend_database: