FROM node:20 AS builder
WORKDIR /app
RUN npm install -g corepack@latest
RUN corepack enable pnpm
COPY ./package.json .
RUN pnpm i
ARG BACKEND_URL
VOLUME [ "/app/node_modules" ]
CMD [ "pnpm", "run", "develop" ]